version: 2
jobs:
  build:
    working_directory: ~/pair-coding-backend
    docker: 
      - image: circleci/node:11.10.0
      - image: mongo:4.0.5
    steps:
      - checkout
      - restore_cache:
          keys: 
            -dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install
          command: npm install
      - save_cache: 
          key: -dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/paircoding-backend.git master